# Generated by Django 2.1.7 on 2019-03-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2018, max_digits=12),
            preserve_default=False,
        ),
    ]
