# Generated by Django 2.1.7 on 2019-03-18 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190317_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competiton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('race_amount', models.IntegerField(default=0)),
                ('start_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
