# Generated by Django 2.1.7 on 2019-03-18 10:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_competiton_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('race_amount', models.IntegerField(default=0)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='events.Event')),
            ],
        ),
        migrations.RemoveField(
            model_name='competiton',
            name='event',
        ),
        migrations.DeleteModel(
            name='Competiton',
        ),
    ]
