# Generated by Django 2.1.7 on 2019-03-18 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190318_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('winner', models.CharField(max_length=80, null=True)),
                ('start_coordinates', models.CharField(max_length=80, null=True)),
                ('finish_coordinates', models.CharField(max_length=80, null=True)),
                ('start_date', models.DateField(null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='events.Competition')),
            ],
        ),
    ]
