# Generated by Django 2.1.7 on 2019-03-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='duration',
            field=models.TimeField(null=True),
        ),
        migrations.AlterModelTable(
            name='competition',
            table='events_competition',
        ),
    ]
