# Generated by Django 2.1.7 on 2019-03-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20190325_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
