# Generated by Django 2.1.7 on 2019-03-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_competition_race_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=80)),
                ('captain_name', models.CharField(max_length=80)),
                ('team_members', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user/images')),
                ('thumbnail', models.ImageField(editable=False, upload_to='user/images/thumbnails')),
            ],
        ),
    ]
