# Generated by Django 2.1.7 on 2019-03-29 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0015_auto_20190328_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='referee',
            field=models.ManyToManyField(blank=True, related_name='user_referee', to=settings.AUTH_USER_MODEL),
        ),
    ]
