# Generated by Django 2.1.7 on 2019-04-16 07:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_gpscoordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpscoordinates',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='events.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpscoordinates',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 7, 46, 35, 195223)),
        ),
    ]
