# Generated by Django 2.1.7 on 2019-04-16 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20190416_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpscoordinates',
            old_name='longtitude',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='gpscoordinates',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 7, 49, 31, 373459)),
        ),
    ]
