# Generated by Django 2.1.7 on 2019-04-30 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20190416_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='checkpoint_coordinates',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='referee_coordinates',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='gpscoordinates',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 13, 8, 55, 682762)),
        ),
    ]
