# Generated by Django 2.1.7 on 2019-05-02 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20190430_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpscoordinates',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 12, 11, 35, 928912)),
        ),
        migrations.AlterField(
            model_name='race',
            name='checkpoint_coordinates',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='finish_coordinates',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='referee_coordinates',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='start_coordinates',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
