# Generated by Django 2.1.7 on 2019-05-03 12:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20190502_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race', to='events.Race')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_result', to='events.Team')),
            ],
        ),
        migrations.AlterField(
            model_name='gpscoordinates',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 15, 3, 14, 603787)),
        ),
    ]
