# Generated by Django 2.1.7 on 2019-05-11 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20190503_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpscoordinates',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 15, 34, 1, 273971)),
        ),
        migrations.AlterField(
            model_name='race',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
